### ISSUE TITLE
Parse error in: LexToken(VAR,'tosca_definitions_version',1,0) 

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-web#148]
Hi,

I am trying to deploy a simple [HelloWorld example](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/csd03/TOSCA-Simple-Profile-YAML-v1.0-csd03.html#_Toc419746196).

However, when I click on "Launch" I always get the following error:
Error: Error: Line 1: Parse error in: LexToken(VAR,'tosca_definitions_version',1,0) 

Br, Borja

**Comment by BorjaEst** [comment]
The docker images I am using:
   - image: grycap/im
   - image: grycap/im-web

**Comment by micafer** [comment]
HI @BorjaEst,
By default im-web portal is using xml-rpc inteface that not support using TOSCA.
You hace to set the im_use_rest configuratio variable to true:

Something like this:
```sh
docker run -p 80:80 -e "im_use_rest=true" -e "im_host=server.domain" -e "im_port=8800" -d grycap/im-web
```

But I will change it in the nest release to use the REST interface as the default one.

**Comment by BorjaEst** [comment]
Hi again,
I tried with the im-cli and I am receiving the same error.
```sh
root@509881c7fbd6:/home# im_client.py create tosca-templates/simple-node.yml 
Connected with: http://172.17.0.1:8899
ERROR creating the infrastructure: Line 1: Parse error in: LexToken(VAR,'tosca_definitions_version',1,0)
```
I tried the im docker versions from https://hub.docker.com/r/grycap/im/:
- 1.9.1
- 1.9.0
- 1.8.0

I am moving so the issue to the im repository.

BR, Borja

**Comment by BorjaEst** [comment]
Thanks!

Now I am getting the following issue:
 - Error: Error: Code: 0. Error connecting to URL: http://localhost:8800/infrastructures?async=yes 

If I try from the cli I get the following:
 - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

I am closing this one and create a new Issue.
