### ISSUE TITLE
Errors when configuring a persisten db

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-web#151]
## Purpose
I would like to make my session data persistent (to save my templates, etc.). Therefore I need to have the database on the host. Following the documentation there is a parameter which indicates the location to place the .db:
[im-web>configuration>im_db](https://imdocs.readthedocs.io/en/latest/web.html)

### Unable to open database file in /var/www/html/im-web/db_sqlite.php
runnning the following command:
```
docker run -p 80:80 -e "im_db=/home/www-data/im.db" -d --name im-web grycap/im-web
```
When I access the im-web url '' I get the following error **after log-in**:
```
Fatal error: Uncaught Exception: Unable to open database: unable to open database file in /var/www/html/im-web/db_sqlite.php:26 Stack trace: #0 /var/www/html/im-web/db_sqlite.php(26): SQLite3->open('/home/www-data/...') #1 /var/www/html/im-web/user.php(65): IMDBSQLite3->__construct() #2 /var/www/html/im-web/list.php(32): check_session_user() #3 {main} thrown in /var/www/html/im-web/db_sqlite.php on line 26
```
If I do an export `docker export im-web > web.tar` I can see there is no such */home/www-data/im.db*, therefore the system complains is not able to open it.

### Attempt to write a readonly database in /var/www/html/im-web/db_sqlite.php
So let's add the database file: I extract the im.db from the web.tar created with export from */var/www/www-data/* and place it in a *./im-web/db* folder with the following docker-compose.yml: 
```yml
  im-web:
    image: grycap/im-web
    container_name: im-web
    environment:
      - im_db=/home/www-data/im.db
    volumes:
      - ./im-web/db:/home/www-data
    ports: 
      - "80:80"
```
Then it is possible to log-in, however, if you try to save a topology using *Topologies > Add+* write something (and a name) and then **Save**, you will get the following error: 
```
Warning: SQLite3::exec(): attempt to write a readonly database in /var/www/html/im-web/db_sqlite.php on line 82

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/im-web/db_sqlite.php:82) in /var/www/html/im-web/user.php on line 26
```
It looks the im-web cannot wrtie into the database.
### The work-arround
It seems you have to give write permissions for everyone (group is not sufficient) to the database file **AND** the folder which contains the data. So you can run:
```
chmod -R a+w im-web/db
```
You do not need to restart the im-web container, you can see directly it is possible to save your templates.

## The change request
I could be possible to explain this procedure in the documentation (or kind of) but I think it would be easier for the users to:
1. If the environment **im_db** is defined, to create automatically the im.db in that location. 
2. It is confusing the name im.db, it made me think it is a file generated by by the im. So at the beginning I tried to link the file generated by "IM_DATA_DB" from the im to the "im_db" from the im-web. I would propose to change "im_db" and "im.db" to "imweb_db" and "im-web.db" by default.
3. Not sure how to solve the issue with the permissions but I am not feeling safe granting writting access to all my users in my computer. Anyone could auto generate his access as admin to the infrastructure web manager.

**Comment by micafer** [comment]
Hi @BorjaEst,

I will try to address your comments.
I will improve the documentation to explain this issues.

First of all to explain that also MySQL servers can be used.

Regarding the permissions, it is commented in the README (https://github.com/grycap/im-web/blob/master/README.md#33-configuration):

"
Path of the IM web interface DB. The original path will be /var/www/im/im.db but is more secure to move it to a path not in the path of the web server. **The file and the directory must have write permissions to the web server user**.
"
In case of docker image is the same.
